#!/usr/bin/env python3.7
"""
This script presents the class ScoreConverter that converts the events
Generated by the System to a score
"""

import os

import music21

import representation.utils as utils


class ScoreConversor:
    """
    A class used to parse a musical file.

    Attributes
    ----------
    """

    def __init__(self):
        self.stream = music21.stream.Stream()

    def parse_events(self, events, new_part=True):
        """
        """
        stream = self.stream
        if new_part:
            stream = music21.stream.Part()

        for event in events:
            print(str(event))
            note = None
            if event.is_rest():
                note = music21.note.Rest(
                    quarterLength=event.get_viewpoint('dur_length'))
            else:
                print(event.get_viewpoint('dnote') + str(int(event.get_viewpoint('octave'))))
                pitch = music21.pitch.Pitch(event.get_viewpoint('dnote') + str(int(event.get_viewpoint('octave'))))
                pitch.ps = event.get_viewpoint('pitch')

                if event.get_viewpoint('accidental') is not music21.pitch.Accidental('natural').modifier:
                    acc = music21.pitch.Accidental('natural')
                    acc.modifier = event.get_viewpoint('accidental')
                    pitch.accidental = acc

                note = music21.note.Note(pitch, quarterLength=event.get_viewpoint('dur_length'))
            stream.append(note)

        if new_part:
            self.stream.append(stream)

        return self.stream
